config/routes.rb
Md::Application.routes.draw do
  resources :posts

  resources :escuelas

  resources :provis

  devise_for :users
  resources :users

	
  get "home/index"

  root :to => "home#index"
  match '/' => "home#index", :as => :home

  match 'gestion'        => 'gestion#index'

  match 'project'        => 'project#index'
  match 'listaesc'       => 'escuelas#listaesc'

  match '/posts/:id/code' => 'posts#show_code', :as => 'show_code'
  match '/escuelas/:id/posts' => 'posts#obrasxesc', :as => 'obrasxesc'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role, :nombre
  # attr_accessible :title, :body

  has_many :posts
  has_many :escuelas, :through => :posts
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# before_filter :require_admin

  # GET /users
  # GET /users.json
  def index
      @users = User.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @users }
      end
  end

  # GET /users/1	
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

    
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">

  <tr class="field">
    <td><%= f.label :nombre %></td>
    <td><%= f.text_field :nombre %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :email %></td>
    <td><%= f.email_field :email %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :password %></td>
    <td><%= f.password_field :password %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :password_confirmation %></td>
    <td><%= f.password_field :password_confirmation %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :role %></td>
    <td><%= f.select( :role, options_for_select(["Admin","Profe"]) ) %></td>
  </tr>
  
  <tr class="actions">
    <td><%= f.submit %></td>
    <td></td>
  </tr>
</table>

<% end %>

app/views/users/edit.html.erb
<div class="container">
<div class="well">

<h1>Editar usuario</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @user %> |
<%= link_to 'Volver', users_path %>

</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="well">

    <h1>Listado de usuarios</h1>

    <div class="navbar">
      <div class="navbar-inner">
        <ul class="nav">
          <li> <%= link_to 'Nuevo usuario', new_user_path %> </li>
          <li> <%= link_to 'Gestionar obras', posts_path %> </li>
          <li> <%= link_to "Gestionar provincias", provis_path %> </li>
          <li> <%= link_to "Gestionar escuelas", escuelas_path %> </li>
        </ul>
      </div>
    </div>

    <table class="table">
      <tr>
        <th>Nombre</th>
        <th>email</th>
        <th>Rol</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.nombre %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Mostrar', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
    </table>

  </div>
</div>

app/views/users/new.html.erb
<div class="container">
<div class="well">

<h3>Nuevo usuario</h3>

<%= render 'form' %>

<%= link_to 'Volver', users_path %>

</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="well">

<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @user.nombre %>
</p>

<p>
  <b>email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Rol:</b>
  <%= @user.role %>
</p>


<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Volver', users_path %>

</div>
</div>